---
created: '2021-06-23T18:06:10.853564Z'
creator: sentry
source: tests/sentry/grouping/test_variants.py
---
app-depth-1:
  hash: "eb87c1031dba55b67df86fb9fff59dc6"
  tree_label: "log_demo::main"
  component:
    app-depth-1*
      exception*
        stacktrace*
          frame* (marked in-app by stack trace rule (family:native function:log_demo::* +app))
            function*
              "log_demo::main"
            package (ignored because function takes precedence)
              "log_demo"
        type*
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
app-depth-2:
  hash: "a6b93019b02cf028eda2609bd65d9fad"
  tree_label: "std::panicking::try::do_call | log_demo::main | log::__private_api_log"
  component:
    app-depth-2*
      exception*
        stacktrace*
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::panicking::try::do_call"
            package (ignored because function takes precedence)
              "std"
          frame* (marked in-app by stack trace rule (family:native function:log_demo::* +app))
            function*
              "log_demo::main"
            package (ignored because function takes precedence)
              "log_demo"
          frame*
            function*
              "log::__private_api_log"
            package (ignored because function takes precedence)
              "log"
        type*
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
app-depth-3:
  hash: "4eb99802a070500823c05725287f0b24"
  tree_label: "___rust_maybe_catch_panic | std::panicking::try::do_call | log_demo::main | log::__private_api_log"
  component:
    app-depth-3*
      exception*
        stacktrace*
          frame*
            function*
              "___rust_maybe_catch_panic"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::panicking::try::do_call"
            package (ignored because function takes precedence)
              "std"
          frame* (marked in-app by stack trace rule (family:native function:log_demo::* +app))
            function*
              "log_demo::main"
            package (ignored because function takes precedence)
              "log_demo"
          frame*
            function*
              "log::__private_api_log"
            package (ignored because function takes precedence)
              "log"
        type*
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
app-depth-4:
  hash: "4a4627b56f14924321050658c1b863ec"
  tree_label: "std::rt::lang_start_internal | ___rust_maybe_catch_panic | std::panicking::try::do_call | log_demo::main | log::__private_api_log"
  component:
    app-depth-4*
      exception*
        stacktrace*
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::rt::lang_start_internal"
            package (ignored because function takes precedence)
              "std"
          frame*
            function*
              "___rust_maybe_catch_panic"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::panicking::try::do_call"
            package (ignored because function takes precedence)
              "std"
          frame* (marked in-app by stack trace rule (family:native function:log_demo::* +app))
            function*
              "log_demo::main"
            package (ignored because function takes precedence)
              "log_demo"
          frame*
            function*
              "log::__private_api_log"
            package (ignored because function takes precedence)
              "log"
        type*
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
app-depth-5:
  hash: "cb57cfc73cc622c2ac1386c9ea531fb9"
  tree_label: "_main | std::rt::lang_start_internal | ___rust_maybe_catch_panic | std::panicking::try::do_call | log_demo::main | log::__private_api_log"
  component:
    app-depth-5*
      exception*
        stacktrace*
          frame*
            function*
              "_main"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::rt::lang_start_internal"
            package (ignored because function takes precedence)
              "std"
          frame*
            function*
              "___rust_maybe_catch_panic"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::panicking::try::do_call"
            package (ignored because function takes precedence)
              "std"
          frame* (marked in-app by stack trace rule (family:native function:log_demo::* +app))
            function*
              "log_demo::main"
            package (ignored because function takes precedence)
              "log_demo"
          frame*
            function*
              "log::__private_api_log"
            package (ignored because function takes precedence)
              "log"
        type*
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
app-depth-max:
  hash: "cb57cfc73cc622c2ac1386c9ea531fb9"
  tree_label: "<entire stacktrace>"
  component:
    app-depth-max*
      exception*
        stacktrace*
          frame*
            function*
              "_main"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::rt::lang_start_internal"
            package (ignored because function takes precedence)
              "std"
          frame*
            function*
              "___rust_maybe_catch_panic"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::panicking::try::do_call"
            package (ignored because function takes precedence)
              "std"
          frame (ignored by stack trace rule (category:internals -group))
            function*
              "std::rt::lang_start::{{closure}}"
            package (ignored because function takes precedence)
              "std"
          frame* (marked in-app by stack trace rule (family:native function:log_demo::* +app))
            function*
              "log_demo::main"
            package (ignored because function takes precedence)
              "log_demo"
          frame*
            function*
              "log::__private_api_log"
            package (ignored because function takes precedence)
              "log"
        type*
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
--------------------------------------------------------------------------
system:
  hash: "cb57cfc73cc622c2ac1386c9ea531fb9"
  tree_label: "<entire stacktrace>"
  component:
    system*
      exception*
        stacktrace*
          frame*
            function*
              "_main"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::rt::lang_start_internal"
            package (ignored because function takes precedence)
              "std"
          frame*
            function*
              "___rust_maybe_catch_panic"
          frame* (marked out of app by stack trace rule (family:native function:std::* -app))
            function*
              "std::panicking::try::do_call"
            package (ignored because function takes precedence)
              "std"
          frame (ignored by stack trace rule (category:internals -group))
            function*
              "std::rt::lang_start::{{closure}}"
            package (ignored because function takes precedence)
              "std"
          frame* (marked in-app by stack trace rule (family:native function:log_demo::* +app))
            function*
              "log_demo::main"
            package (ignored because function takes precedence)
              "log_demo"
          frame*
            function*
              "log::__private_api_log"
            package (ignored because function takes precedence)
              "log"
        type*
          "log_demo"
        value (ignored because stacktrace takes precedence)
          "Holy shit everything is on fire!"
