---
created: '2025-09-24T20:27:06.335316+00:00'
creator: sentry
source: tests/sentry/grouping/test_variants.py
---
app:
  hash: "d505dfb9059ac63c11955233323a9100"
  contributing component: chained_exception
  root_component:
    app*
      chained_exception*
        exception*
          stacktrace*
            frame* (marked in-app by the client)
              module*
                "dostuff"
              function*
                "do_stuff"
            frame* (marked in-app by the client)
              module*
                "dostuff"
              function*
                "do_different_stuff"
          type*
            "DoStuffException"
          value (ignored because stacktrace takes precedence)
            "Can't do the stuff"
        exception*
          stacktrace*
            frame* (marked in-app by the client)
              module*
                "dostuff"
              function*
                "do_other_stuff"
            frame (marked in-app by the client but ignored due to recursion)
              module*
                "dostuff"
              function*
                "do_other_stuff"
          type*
            "DoOtherStuffException"
          value (ignored because stacktrace takes precedence)
            "Can't do the other stuff"
        exception*
          type*
            "System.AggregateException"
          value*
            "One or more errors occurred."
--------------------------------------------------------------------------
system:
  hash: "4f9cc6a81f4eb34f9e917374f281b9dc"
  contributing component: chained_exception
  root_component:
    system*
      chained_exception*
        exception*
          stacktrace*
            frame*
              module*
                "dostuff"
              function*
                "do_stuff"
            frame*
              module*
                "dostuff"
              function*
                "do_different_stuff"
          type*
            "DoStuffException"
          value (ignored because stacktrace takes precedence)
            "Can't do the stuff"
        exception*
          stacktrace*
            frame*
              module*
                "dostuff"
              function*
                "do_other_stuff"
            frame (ignored due to recursion)
              module*
                "dostuff"
              function*
                "do_other_stuff"
          type*
            "DoOtherStuffException"
          value (ignored because stacktrace takes precedence)
            "Can't do the other stuff"
